# Generated by Django 4.2.4 on 2023-08-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_1', models.FloatField()),
                ('input_2', models.FloatField()),
                ('input_3', models.FloatField()),
                ('input_4', models.FloatField()),
                ('input_5', models.FloatField()),
                ('input_6', models.FloatField()),
                ('input_7', models.FloatField()),
                ('input_8', models.FloatField()),
                ('input_9', models.FloatField()),
                ('input_10', models.FloatField()),
                ('input_11', models.FloatField()),
                ('input_12', models.FloatField()),
                ('input_13', models.FloatField()),
                ('input_14', models.FloatField()),
                ('input_15', models.FloatField()),
                ('input_16', models.FloatField()),
                ('input_17', models.FloatField()),
                ('input_18', models.FloatField()),
                ('input_19', models.FloatField()),
                ('input_20', models.FloatField()),
                ('input_21', models.FloatField()),
                ('input_22', models.FloatField()),
                ('input_23', models.FloatField()),
                ('input_24', models.FloatField()),
                ('input_25', models.FloatField()),
                ('input_26', models.FloatField()),
                ('input_27', models.FloatField()),
                ('input_28', models.FloatField()),
                ('input_29', models.FloatField()),
                ('input_30', models.FloatField()),
                ('input_31', models.FloatField()),
                ('input_32', models.FloatField()),
                ('input_33', models.FloatField()),
                ('input_34', models.FloatField()),
                ('input_35', models.FloatField()),
                ('input_36', models.FloatField()),
                ('input_37', models.FloatField()),
                ('input_38', models.FloatField()),
                ('input_39', models.FloatField()),
                ('input_40', models.FloatField()),
                ('input_41', models.FloatField()),
                ('input_42', models.FloatField()),
                ('input_43', models.FloatField()),
                ('input_44', models.FloatField()),
                ('input_45', models.FloatField()),
                ('input_46', models.FloatField()),
                ('input_47', models.FloatField()),
                ('input_48', models.FloatField()),
                ('result', models.FloatField()),
            ],
        ),
    ]
